# To run do:
#
# docker-compose build
# docker-compose up -d web
#
db:
  # Note you cannot scale if you use conteiner_name
  container_name: db.demo.qgis.org
  image: kartoza/postgis:9.4-2.1
  volumes:
    #- ./pg/postgres_data:/var/lib/postgresql
    - ./backups:/backups
  environment:
    - USERNAME=docker
    - PASS=docker
  restart: on-failure:5

btsync:
  image: kartoza/btsync
  container_name: btsync.demo.qgis.org
  hostname: btsync.demo.qgis.org
  volumes:
    - /web
  environment:
    # This should be the read only key
    - SECRET=BRKIFB3PYGOXTDBOWXH6G4UCN2GYZV5ER
    - DEVICE=readonly-demo.qgis.org
  restart: on-failure:5

qgis-server:
  image: kartoza/qgis-server
  hostname: demo.qgis.org
  container_name: demo.qgis.org
  volumes_from: 
    - btsync
  volumes:
    - ./logs:/var/log/apache2
  links:
    - db:db
  ports:
    - 8198:80 
  restart: on-failure:5

